apiVersion: v1
kind: Secret
metadata:
  namespace: kube-system
  name: csi-s3-secret
stringData:
  accessKeyID: YCAJEaPPg9CA8HPqogJ8dhqea
  secretAccessKey: YCPcO2fi-fhpb8nLzo9fDynGSZxHo_G6ry64kewo
  # For AWS set it to "https://s3.<region>.amazonaws.com", for example https://s3.eu-central-1.amazonaws.com
  endpoint: https://storage.yandexcloud.net
  # For AWS set it to AWS region
  #region: ""