apiVersion: v1
kind: Pod
metadata:
  name: homework-pod
  namespace: homework
spec:
  containers:
  - name: web-server
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
    lifecycle:
      preStop:
        exec:
          command: ["/bin/sh", "-c", "rm -f /usr/share/nginx/html/index.html"]
  initContainers:
  - name: init-container
    image: busybox
    command: ['sh', '-c', 'echo "<h1>Hello, Kubernetes!</h1>" > /init/index.html']
    volumeMounts:
    - name: shared-data
      mountPath: /init
  volumes:
  - name: shared-data
    emptyDir: {}