apiVersion: v1
kind: Pod
metadata:
  name: nginx-distroless
  labels:
    app: nginx-distroless
spec:
  shareProcessNamespace: true
  containers:
  - name: nginx
    image: kyos0109/nginx-distroless
    securityContext:
      privileged: true
      capabilities:
        add:
        - SYS_PTRACE
    ports:
    - containerPort: 80