apiVersion: v1
kind: Service
metadata:
  name: homework-service
  namespace: homework
spec:
  nodeSelector:
    node-role.kubernetes.io/infra: ""  # Убедитесь, что эта метка есть на нужных нодах
  tolerations:
    - key: "node-role"
      operator: "Equal"
      value: "infra"
      effect: "NoSchedule"
  selector:
    app: homework
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
