replicaCount: 3

image:
  repository: myrepo/myapp
  tag: 1.0.0
  pullPolicy: IfNotPresent

service:
  name: myapp-service
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

livenessProbe:
  enabled: true
  httpGet:
    path: /healthz
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 30
  failureThreshold: 3

readinessProbe:
  enabled: true
  httpGet:
    path: /readiness
    port: http
  initialDelaySeconds: 30
  timeoutSeconds: 30
  failureThreshold: 3

serviceAccount:
  create: true
  name: ""


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

mysql:
  enabled: true
  auth:
    rootPassword: "root_password"
    username: "user"
    password: "password"
    database: "myapp_db"
