apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: custom-nginx-servicemonitor
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: custom-nginx
  endpoints:
  - port: metrics
    interval: 15s