apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-nginx-deployment
  labels:
    app: custom-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-nginx
  template:
    metadata:
      labels:
        app: custom-nginx
    spec:
      containers:
      - name: custom-nginx
        image: autotestagent/containerimages:latest
        ports:
        - containerPort: 80
        - containerPort: 9113
---
apiVersion: v1
kind: Service
metadata:
  name: custom-nginx-service
  labels:
    app: custom-nginx
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 9113
      targetPort: 9113
      protocol: TCP
      name: metrics
  selector:
    app: custom-nginx
