apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: otus-cred
  namespace: vault
spec:
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: otus-cred
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: otus/cred
      property: username
  - secretKey: password
    remoteRef:
      key: otus/cred
      property: password
