apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: vault
spec:
  provider:
    vault:
      server: "http://vault-server-0.vault-server-headless:8200"
      path: "kv/data"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "auth/kubernetes"
          role: "otus"
          serviceAccountRef:
            name: "vault-auth"