apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault-server
  namespace: vault
spec:
  template:
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          volumeMounts:
            - name: policy-volume
              mountPath: /vault/policies
      volumes:
        - name: policy-volume
          configMap:
            name: vault-policy-config